function getBoardDataFromTestData() {
  // sample JSON generated by ChatGPT from prompt
  // will need to make pre-seeded prompt for future requests
  
  return `{
    "Name": "Animal Cells Review",
    "Categories": [
      {
        "Name": "Cell Structures",
        "Boxes": [
          {
            "Question": "This organelle is responsible for producing energy in the cell.",
            "Answer": "Mitochondria",
            "Value": 100
          },
          {
            "Question": "Which organelle is responsible for protein synthesis?",
            "Answer": "Ribosomes",
            "Value": 200
          },
          {
            "Question": "This structure acts as the control center of the cell.",
            "Answer": "Nucleus",
            "Value": 300
          },
          {
            "Question": "Which organelle is responsible for packaging and distributing proteins?",
            "Answer": "Golgi apparatus",
            "Value": 400
          },
          {
            "Question": "This organelle is responsible for detoxifying harmful substances in the cell.",
            "Answer": "Smooth endoplasmic reticulum",
            "Value": 500
          }
        ]
      },
      {
        "Name": "Cell Types",
        "Boxes": [
          {
            "Question": "This type of animal cell lacks a cell wall.",
            "Answer": "Animal cells",
            "Value": 100
          },
          {
            "Question": "Which type of cell has a single, circular chromosome?",
            "Answer": "Prokaryotic cells",
            "Value": 200
          },
          {
            "Question": "This type of cell has membrane-bound organelles.",
            "Answer": "Eukaryotic cells",
            "Value": 300
          },
          {
            "Question": "Which type of cell has a rigid cell wall made of cellulose?",
            "Answer": "Plant cells",
            "Value": 400
          },
          {
            "Question": "This type of cell has a large central vacuole.",
            "Answer": "Plant cells",
            "Value": 500
          }
        ]
      },
      {
        "Name": "Cell Processes",
        "Boxes": [
          {
            "Question": "This process allows cells to divide and reproduce.",
            "Answer": "Cell division/mitosis",
            "Value": 100
          },
          {
            "Question": "Which process involves the movement of molecules from an area of higher concentration to an area of lower concentration?",
            "Answer": "Diffusion",
            "Value": 200
          },
          {
            "Question": "This process involves the breaking down of glucose to produce ATP.",
            "Answer": "Cellular respiration",
            "Value": 300
          },
          {
            "Question": "Which process involves the conversion of light energy into chemical energy?",
            "Answer": "Photosynthesis",
            "Value": 400
          },
          {
            "Question": "This process allows cells to take in large particles by engulfing them.",
            "Answer": "Endocytosis",
            "Value": 500
          }
        ]
      },
      {
        "Name": "Cell Functions",
        "Boxes": [
          {
            "Question": "This cell structure helps maintain the shape and provide support.",
            "Answer": "Cell wall",
            "Value": 100
          },
          {
            "Question": "Which organelle contains enzymes for intracellular digestion?",
            "Answer": "Lysosome",
            "Value": 200
          },
          {
            "Question": "This organelle is responsible for synthesizing lipids.",
            "Answer": "Smooth endoplasmic reticulum",
            "Value": 300
          },
          {
            "Question": "Which organelle is responsible for detoxifying harmful substances in the cell?",
            "Answer": "Smooth endoplasmic reticulum",
            "Value": 400
          },
          {
            "Question": "This organelle stores water, ions, and nutrients.",
            "Answer": "Vacuole",
            "Value": 500
          }
        ]
      },
      {
        "Name": "Cell Division",
        "Boxes": [
          {
            "Question": "This phase of the cell cycle involves DNA replication.",
            "Answer": "S phase",
            "Value": 100
          },
          {
            "Question": "Which phase of mitosis involves the separation of sister chromatids?",
            "Answer": "Anaphase",
            "Value": 200
          },
          {
            "Question": "This term refers to the division of the cytoplasm following nuclear division.",
            "Answer": "Cytokinesis",
            "Value": 300
          },
          {
            "Question": "Which phase of mitosis involves the arrangement of chromosomes at the cell equator?",
            "Answer": "Metaphase",
            "Value": 400
          },
          {
            "Question": "This term refers to the period of cell growth and preparation for division.",
            "Answer": "Interphase",
            "Value": 500
          }
        ]
      },
      {
        "Name": "Cell Membrane",
        "Boxes": [
          {
            "Question": "This lipid forms the major component of the cell membrane.",
            "Answer": "Phospholipids",
            "Value": 100
          },
          {
            "Question": "Which type of transport requires energy to move substances across the cell membrane against the concentration gradient?",
            "Answer": "Active transport",
            "Value": 200
          },
          {
            "Question": "This term refers to the tendency of molecules to spread out evenly into the available space.",
            "Answer": "Equilibrium",
            "Value": 300
          },
          {
            "Question": "Which type of transport does not require energy and moves substances from an area of higher concentration to an area of lower concentration?",
            "Answer": "Passive transport",
            "Value": 400
          },
          {
            "Question": "This structure helps cells communicate and coordinate their activities.",
            "Answer": "Cell membrane receptors",
            "Value": 500
          }
        ]
      }
    ]
  }`
}